services:
    david63.dropboxupload.listener:
        class: david63\dropboxupload\event\listener
        arguments:
            - '@config'
            - '@user'
            - '@log'
            - '@language'
        tags:
            - { name: event.listener }

    david63.dropboxupload.admin.controller:
        class: david63\dropboxupload\controller\admin_controller
        arguments:
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@log'
