imports:
    - { resource: alias.yml }

services:
    _defaults:
        autowire: true
        bind:
            $ext_images_path: '%core.root_path%ext/david63/announceonindex/adm/style/images'
        public: true

    david63.dropboxupload.listener:
        class: david63\dropboxupload\event\listener
        tags:
            - { name: event.listener }

    david63.dropboxupload.admin.controller:
        class: david63\dropboxupload\controller\admin_controller

    david63.dropboxupload.main.controller:
        class: david63\dropboxupload\controller\main_controller

    david63.dropboxupload.core.functions:
        class: david63\dropboxupload\core\functions
